### PR TITLE
Fix file descriptor leak

### LINKED ISSUE #275: The loop of file writing causes the "No file descriptors available" error
## Steps to reproduce

1. `git clone https://github.com/swiftwasm/WasmKit`
2. `cd WasmKit`
3. `swift build -c release`
4. `cd ..`
5. `mkdir wasi-file-create-remove-loop`
6. `cd wasi-file-create-remove-loop`
7. `swift package init --type executable`
8. Edit `Sources/wasi-file-create-remove-loop/wasi-file-create-remove-loop.swift`
	```swift
	import Foundation

	@main
	struct wasi_file_create_remove_loop {
	    static func main() throws {
	        try FileManager.default.createDirectory(atPath: "foo", withIntermediateDirectories: true)
	        for i in 0..<100 {
	            guard FileManager.default.createFile(atPath: "foo/bar", contents: Data()) else {
	                fatalError("#\(i): failed to create a file")
	            }
	            try FileManager.default.removeItem(atPath: "foo/bar")
	        }
	        try FileManager.default.removeItem(atPath: "foo")
	        print("success")
	    }
	}
	```
9. `swift build --swift-sdk "$(swiftc -print-target-info | jq -r '.swiftCompilerTag')_wasm"`
10. `../WasmKit/.build/release/wasmkit-cli run --dir . .build/debug/wasi-file-create-remove-loop.wasm`

## Expected behavior

```console
$ wasmtime run --dir . .build/debug/wasi-file-create-remove-loop.wasm
success
```

## Actual behavior

```console
$ ../WasmKit/.build/release/wasmkit-cli run --dir . .build/debug/wasi-file-create-remove-loop.wasm
wasi_file_create_remove_loop/wasi_file_create_remove_loop.swift:9: Fatal error: #84: failed to create a file
Error: Trap: unreachable
    0: (0x000000084a77df80) $ss17_assertionFailure__4file4line5flagss5NeverOs12StaticStringV_SSAHSus6UInt32VtF
    1: (0x000000084547c538) $s28wasi_file_create_remove_loopAAV4mainyyKFZ
    2: (0x00000008454a4790) $s28wasi_file_create_remove_loopAAV5$mainyyKFZ
    3: (0x000000084a72ccc0) main
    4: (0x000000084a7100c0) __main_void
    5: (0x000000016b7d6a78) _start
    6: (0x0000000100000003) unknown
```

## Environment

- macOS 26.2 aarch64
- M4 Mac mini
- Swift main-snapshot-2026-01-09
    ```console
    $ swift --version
    Apple Swift version 6.3-dev (LLVM d402ab9729f318e, Swift 2de856568572fc0)
    Target: arm64-apple-macosx26.0
    Build config: +assertions
    ```
- Wasm SDK: `swift-DEVELOPMENT-SNAPSHOT-2026-01-09-a_wasm`
- WasmKit main branch a654a899a0e2802bf66429214e8ebc51c397c4d9
- wasmtime 40.0.2

### PR DESCRIPTION
**Pull request by kkebo**
fixes #275 

I have completely eliminated the possibility of a close leak occurring in file descriptors opened with `SandboxPrimitives.openParent` using a non-copyable type.

### CODE REVIEW

File: Tests/WASITests/WASITests.swift [hunk 1]
```diff
@@ -1347,4 +1347,34 @@ struct WASITests {
...
+            let t = try TestSupport.TemporaryDirectory()
+
+            let wasi = try WASIBridgeToHost(
+                fileSystem: .host().withPreopens([
+                    .init(guestPath: "/", hostPath: t.url.path)
+                ])
+            ).underlying
+            let preopenFd: WASIAbi.Fd = 3
+
+            for _ in 0...10000 {
```
Comment (kkebo) [inline Tests/WASITests/WASITests.swift]: Isn't there a more efficient leak detection method?

Comment (kkebo) [reply Tests/WASITests/WASITests.swift]: I improved the test.

5bbb05e8bd9d7f365a0120406aa3208d0cc9528c

Comment (kkebo) [reply Tests/WASITests/WASITests.swift]: I made a mistake. swift-testing test cases are executed in parallel, so `before` and `after` may not be accurate.

**Review by kateinoigakukun — APPROVED** [review]
